name: clean_architecture_news
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #state management
  flutter_bloc: ^8.1.3
  #comparing dart objects
  equatable: ^2.0.5
  #service locator
  get_it: ^7.6.7
  #dateFormat
  intl: ^0.19.0
  #Database
  floor: ^1.4.2
  #make request to api
  retrofit: ^4.0.3
  #Hooks
  flutter_hooks: ^0.20.4
  #chached image 
  cached_network_image: ^3.3.1
  #HTTP networking
  dio: ^5.4.0
  sqflite: ^2.3.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2


flutter:

  uses-material-design: true
  
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
          
  
  
